; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.31"

; Modules
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.2"

projects[admin_views][subdir] = "contrib"
projects[admin_views][version] = "1.3"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[article][download][type] = ""
projects[article][download][url] = ""
projects[article][type] = "module"
projects[article][subdir] = "features"
projects[article][version] = "1.0"

projects[breakpoints][subdir] = "contrib"
projects[breakpoints][version] = "1.2"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"

projects[color_field][subdir] = "contrib"
projects[color_field][version] = "1.6"

projects[context][subdir] = "contrib"
projects[context][version] = "3.2"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[ds][subdir] = "contrib"
projects[ds][version] = "2.6"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[entity_translation][subdir] = "contrib"
projects[entity_translation][version] = "1.0-beta3"

projects[features][subdir] = "contrib"
projects[features][version] = "2.2"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta7"
;projects[field_collection][patch][1344672] = http://www.drupal.org/files/issues/field_collection-et-1344672-248.patch"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.4"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[home][download][type] = ""
projects[home][download][url] = ""
projects[home][type] = "module"
projects[home][subdir] = "features"
projects[home][version] = "1.0"

projects[i18n][subdir] = "contrib"
projects[i18n][version] = "1.11"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.4"

projects[l10n_update][subdir] = "contrib"
projects[l10n_update][version] = "1.0"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.2"

projects[linkit][subdir] = "contrib"
projects[linkit][version] = "3.1"

projects[manualcrop][subdir] = "contrib"
projects[manualcrop][version] = "1.4"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.4"

projects[menu_position][subdir] = "contrib"
projects[menu_position][version] = "1.1"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0-alpha2"

projects[navbar][subdir] = "contrib"
projects[navbar][version] = "1.4"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[page][download][type] = ""
projects[page][download][url] = ""
projects[page][type] = "module"
projects[page][subdir] = "features"
projects[page][version] = "1.0"

projects[ad][download][type] = ""
projects[ad][download][url] = ""
projects[ad][type] = "module"
projects[ad][subdir] = "features"
projects[ad][version] = "1.0"

projects[education][download][type] = ""
projects[education][download][url] = ""
projects[education][type] = "module"
projects[education][subdir] = "features"
projects[education][version] = "1.0"

projects[project][download][type] = ""
projects[project][download][url] = ""
projects[project][type] = "module"
projects[project][subdir] = "features"
projects[project][version] = "1.0"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[migrate][version] = 2.5
projects[migrate][subdir] = contrib

projects[migrate_extras][download][type] = "git"
projects[migrate_extras][download][url] = "git://drupalcode.org/project/migrate_extras.git"
projects[migrate_extras][download][revision] = "02fcb71ab059a7baa178afd9f59e586145da55e1"
projects[migrate_extras][destination] = modules
projects[migrate_extras][directory_name] = contrib/migrate_extras
projects[quickedit][subdir] = "contrib"
projects[quickedit][version] = "1.1"

projects[eu_cookie_compliance][version] = 1.14
projects[eu_cookie_compliance][subdir] = contrib

projects[responsive_preview][subdir] = "contrib"
projects[responsive_preview][version] = "1.1"

projects[simplified_menu_admin][subdir] = "contrib"
projects[simplified_menu_admin][version] = "1.0-beta2"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[title][subdir] = "contrib"
projects[title][version] = "1.0-alpha7"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[transliteration][subdir] = "contrib"
projects[transliteration][version] = "3.2"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

projects[webform][subdir] = "contrib"
projects[webform][version] = "3.20"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

; Themes
projects[ember][subdir] = "contrib"
projects[ember][version] = "2.0-alpha2"

projects[zen][subdir] = "contrib"
projects[zen][version] = "5.5"


; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery-simple-color][download][type] = ""
libraries[jquery-simple-color][download][url] = ""
libraries[jquery-simple-color][directory_name] = "jquery-simple-color"
libraries[jquery-simple-color][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.imagesloaded][download][type] = ""
libraries[jquery.imagesloaded][download][url] = ""
libraries[jquery.imagesloaded][directory_name] = "jquery.imagesloaded"
libraries[jquery.imagesloaded][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.imgareaselect][download][type] = ""
libraries[jquery.imgareaselect][download][url] = ""
libraries[jquery.imgareaselect][directory_name] = "jquery.imgareaselect"
libraries[jquery.imgareaselect][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[json2][download][type] = ""
libraries[json2][download][url] = ""
libraries[json2][directory_name] = "json2"
libraries[json2][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[markitup][download][type] = ""
libraries[markitup][download][url] = ""
libraries[markitup][directory_name] = "markitup"
libraries[markitup][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = ""
libraries[modernizr][download][url] = ""
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[respondjs][download][type] = ""
libraries[respondjs][download][url] = ""
libraries[respondjs][directory_name] = "respondjs"
libraries[respondjs][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[SolrPhpClient][download][type] = ""
libraries[SolrPhpClient][download][url] = ""
libraries[SolrPhpClient][directory_name] = "SolrPhpClient"
libraries[SolrPhpClient][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tinymce][download][type] = ""
libraries[tinymce][download][url] = ""
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

